# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.5.0
      - uses: bufbuild/buf-lint-action@v1
      - name: buf-lint
        uses: bufbuild/buf-lint-action@v1.0.0
